version: "3.2"

services:
  portal_app:
    image: google/cloud-sdk:160.0.0
    volumes:
    - ./:/app:ro
    entrypoint: dev_appserver.py -A relayerdev --env_var DATASTORE_EMULATOR_HOST=gcloud_datastore:8889 --host 0.0.0.0 --port 8090 /app/app.yaml
    ports:
    - "8090:8090"
  gcloud_datastore:
    image: google/cloud-sdk:160.0.0
    volumes:
    - data:/data
    entrypoint: gcloud beta emulators datastore start --project=relayerdev --host-port localhost:8889 --data-dir=/data
    ports:
    - "8889:8889"

volumes:
  data:
